name: Publish to NPM

on:
  push:
    branches:
      - beta/**

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
    
      - name: Create token
        run: echo ${{secrets.AUTH_TOKEN}} > /root/.npmrc
        
      - name: Install deps
        run: yarn
      
      # - name: Version
      #   run: npm version 
      
      - name: Publish
        run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
